version: '3.9'
networks:
  pvapi:

services:
  pvapi:
    image: pvapi
    networks:
      - pvapi
    restart: unless-stopped
    container_name: pvapi
    build:
      dockerfile: "./VPS.dockerfile"
    ports:
      - "8005:80"
